### ISSUE TITLE
A user can search summoner info.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/LoL-Stats#1]
**Wireframe**

![screen shot 2018-04-23 at 3 25 26 pm](https://user-images.githubusercontent.com/22861295/39156669-11ea7588-470c-11e8-9049-259cdeb6ba54.png)

**Data**

![screen shot 2018-04-23 at 3 25 39 pm](https://user-images.githubusercontent.com/22861295/39156680-269b30b2-470c-11e8-99bf-d28a1b7df451.png)

**Tasks**

- [ ] Acquire Riot Games API key.
- [ ] Set up project environment.
- [ ] Create static page using React.
- [ ] Searching with valid username will log summoner.
