### ISSUE TITLE
A user can view match details.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/LoL-Stats#22]
**Motivation**
To put the stats in LoL Stats.

**Wireframe**

![new wireframe](https://user-images.githubusercontent.com/22861295/44048784-3a8eaee0-9ee7-11e8-9aab-72dac3470715.png)

**Component Heirarchy**

```javascript
<MatchDetails>
  <Stats />
  <Graph />
<MatchDetails>
```

**Tasks**

- [x] Move state up so matches data can be passed to matches details.
- [x] Read ChartJS documentation.
- [x] Build static component.
- [x] Implement live data to component.
- [x] Clicking on a match will render that specific matches info.

**Comment by anthonyrodarte** [comment]
![LoL Stats Gif](https://media.giphy.com/media/fnjy2EOkjiIZMzbt1h/giphy.gif)
