### ISSUE TITLE
A user can search from match results page.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/LoL-Stats#29]
**Motivation**

The user should be able to search from the page where the stats are displayed in order to improve user experience.

**Wireframe**

![screen shot 2018-08-23 at 10 44 04 am](https://user-images.githubusercontent.com/22861295/44542393-854b3e80-a6c1-11e8-9487-8bb85fedc1b6.png)

**Tasks**

- [x] Build static component
- [x] Lift state up to app component
- [x] Add functionality to search bar
