### ISSUE TITLE
A user can view summoner details.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/LoL-Stats#5]
**Wireframe**

![screen shot 2018-05-01 at 1 29 15 pm](https://user-images.githubusercontent.com/22861295/39492213-bec9f1a6-4d43-11e8-8841-023c3dc33930.png)

Fetched Data

```javascript
{
    "matches": [
  {
            "lane": "MID",
            "gameId": 2751023682,
            "champion": 105,
            "platformId": "NA1",
            "timestamp": 1522373330674,
            "queue": 420,
            "role": "SOLO",
            "season": 11
        } 
  ],
    "endIndex": 20,
    "startIndex": 0,
    "totalGames": 178
}
```

JS Data
```javascript
const matches = [
 {
  lane: "MID",
  game: 2751023682,
  champion: 105,
  platformId: "NA1",
  timestamp: 1522373330674,
  queue: 420,
  role: "SOLO",
  season: 11
}
]
```

**Tasks**

- [x] Create function to acquire summoner rank.
- [x] Create route for summoner rank.
- [x] Create function for summoner match history.
- [x] Create route for summoner match history.
- [x] Create function for match details.
- [x] Create route for match details.
- [x] Acquire images for banner and rank icons.
- [x] Build static component.
- [x] Create fetch request for rank.
- [x] Create fetch request for match history.
- [x] Create fetch request for match details.
- [x] Build function that finds the summoners match result within the match details.
- [x] Render matches based on match history.

**Refactor**

- [x] Combine error handling with express middleware.
- [x] Combine Backend API requests into a service object.
- [x] Combine Frontend API requests into a service object.
- [x] Pull pure functions out of rendering logic.
- [x] Use short-circuit rendering instead of ternaries.

**Comment by anthonyrodarte** [comment]
Reopening to add better styling. Will stray from wireframe a bit.
