### ISSUE TITLE
Implement automated server tests.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/LoL-Stats#8]
**Motivation**

Testing consistently ensures that the code is running correctly.

**Tasks**

- [x] Install dependencies Nock, Mocha, nyc, and Chai.
- [x] Set up test directory, script, and example test.
- [x] Add code coverage report
- [x] Implement the test  
  - [x] Get /search?name
  - [x] Get /rank?id
  - [x] Get /match?id
  - [x] Get /matches?id
  - [x] Get /icon?id
